services:
  db:
    image: postgres:16-alpine
    container_name: dba_challenge_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dba_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: